DROP DATABASE IF EXISTS Project201;
CREATE DATABASE Project201;

USE Project201;
    
CREATE TABLE Users (
  UserID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  fName VARCHAR(45) NOT NULL,
  Email VARCHAR(45) NOT NULL,
  pwd VARCHAR(45) NOT NULL,
  AccountType VARCHAR(45) NOT NULL
);
  
CREATE TABLE Courses (
  CourseID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  CourseName VARCHAR(10) NOT NULL
);
  
CREATE TABLE Sessions (
  SessionID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  UserID INT NOT NUll, 
  CourseID INT NOT NULL, 
  StartTime VARCHAR(45) NOT NULL, 
  EndTime VARCHAR(45) NOT NULL,
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (CourseID) REFERENCES Cousrses(CourseID)
);
  
CREATE TABLE Favorites (
  FavoriteID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  UserID INT NOT NULL,
  CourseID INT NOT NULL,
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (CourseID) REFERENCES Cousrses(CourseID)
);